name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Unit Tests
      run: mvn test

    - name: Upload Unit Test Results
      if: always() # This ensures the results are uploaded even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: Unit-Test-Results
        path: target/surefire-reports/*.xml # This is where the JUnit results are stored

    - name: Run System Tests
      run: |
        java -cp target/PizzaDronz-1.0-SNAPSHOT.jar uk.ac.ed.inf.SystemTests.Driver

    - name: Upload System Test Results
      if: always() # Ensure test results are uploaded even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: System-Test-Results
        path: target/system-tests-reports/*.xml # Adjust this path if system tests generate reports elsewhere
